name: ELIS - Agent Nightly
# =============================================================================
# Purpose
#   Nightly verification + run. First, strictly verify the canonical C filename:
#     json_jsonl/ELIS_Appendix_C_DataExtraction_rows.json
#   If the check passes, run the nightly agent. No file mutations are performed.
#
# Why this change
#   Lock the invariant for Appendix C naming across time without introducing
#   any "safe shim" or auto-rename step. Fail loudly if drift appears.
# =============================================================================

on:
  schedule:
    - cron: "10 2 * * *"  # daily at 02:10 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  actions: read

jobs:
  nightly-verify-and-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Verify-only guard for the canonical C filename (no renames, no shims).
      - name: Verify canonical Appendix C filename
        run: |
          set -euo pipefail
          CANONICAL="json_jsonl/ELIS_Appendix_C_DataExtraction_rows.json"

          # Exact path must exist
          if [[ ! -f "$CANONICAL" ]]; then
            echo "::error::Missing canonical file at $CANONICAL."
            exit 2
          fi

          # No other Appendix C files lurking nearby (e.g., ..._Extraction_..., JSONL, etc.)
          mapfile -t VARIANTS < <(find json_jsonl -maxdepth 1 -type f \
            -iregex '.*/ELIS[ _-]*Appendix[ _-]*C[ _-]*.*rows\.\(json\|jsonl\)$' \
            ! -path "$CANONICAL")
          if (( ${#VARIANTS[@]} > 0 )); then
            printf '%s\n' "${VARIANTS[@]}" | sed 's/^/::error::Found non-canonical C variant: /'
            exit 3
          fi

          # Optional: if jq is present, ensure the file is a JSON array (best-effort).
          if command -v jq >/dev/null 2>&1; then
            jq -e 'type=="array"' "$CANONICAL" >/dev/null || (echo "::error::C file must be a JSON array"; exit 5)
          fi

          echo "✅ Canonical C path verified."

      # Run your nightly agent only when verification passes.
      - name: Run ELIS Agent (nightly)
        if: ${{ success() }}
        env:
          ELIS_ENV: nightly
        run: |
          # Replace with your nightly entrypoint
          # Example: python -m elis.agent nightly
          echo "Run your ELIS nightly agent here..."
