name: ELIS - Agent Run
# -----------------------------------------------------------------------------
# Purpose
#   Run the toy agent (scripts/agent.py) to generate MVP artefacts under
#   json_jsonl/, then upload that folder as a downloadable workflow artifact.
#
# Notes
#   - This workflow is read-only: it does not push branches or open PRs.
#     (We can add an auto-PR mode in a later step.)
# -----------------------------------------------------------------------------

on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Git ref to run against (branch or tag). Defaults to main."
        required: false
        default: "main"

permissions:
  contents: read

jobs:
  run-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main (or provided ref)
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref || 'main' }}
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install minimal runtime
        run: |
          python -m pip install --upgrade pip
          # requirements.txt is minimal and present in repo
          pip install -r requirements.txt || true

      - name: Run Toy Agent
        run: |
          python scripts/agent.py

      - name: List artefacts
        run: |
          echo "==> json_jsonl/"
          ls -la json_jsonl || true
          echo "==> json_jsonl/config (if present)"
          ls -la json_jsonl/config || true
          echo "==> json_jsonl/logs (if present)"
          ls -la json_jsonl/logs || true

      - name: Upload artefacts (json_jsonl/)
        uses: actions/upload-artifact@v4
        with:
          name: json_jsonl
          path: |
            json_jsonl/**
          if-no-files-found: error
          retention-days: 14
