name: ELIS - Autoformat
# ============================================================================
# Purpose
#   Run Black on a target branch (default: `elis-bot`). If changes occur,
#   commit and push them, then (optionally) open/refresh a PR into `main`.
#
# Why this fixes red jobs
#   • Skip PR creation when head == base via an API diff check (no 422).
#   • Robust sync handles unrelated histories/dirty trees on the bot branch.
#   • Force LF line endings + .gitattributes renormalisation to prevent Black churn.
#   • Use github.event.inputs.* (reliable) instead of inputs.* in top-level/concurrency.
# ============================================================================

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: "Base branch to PR into"
        required: false
        default: "main"
      target_branch:
        description: "Branch to autoformat (in-place)"
        required: false
        default: "elis-bot"
      open_pr:
        description: "Open/refresh PR target_branch → base_branch"
        required: false
        default: "true"

permissions:
  contents: write
  pull-requests: write

# Use workflow_dispatch inputs safely at top-level (concurrency supports expressions)
concurrency:
  group: autoformat-${{ github.event.inputs.target_branch != '' && github.event.inputs.target_branch || 'elis-bot' }}
  cancel-in-progress: false

jobs:
  autoformat:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    env:
      # Normalise access to inputs (provide defaults in shell where needed)
      BASE_BRANCH:   ${{ github.event.inputs.base_branch }}
      TARGET_BRANCH: ${{ github.event.inputs.target_branch }}
      OPEN_PR:       ${{ github.event.inputs.open_pr }}

    steps:
      # 1) GitHub App token for write operations
      - name: Mint installation token (GitHub App)
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ELIS_APP_ID }}
          private-key: ${{ secrets.ELIS_APP_PRIVATE_KEY }}

      # 2) Checkout repo (we'll position to the target branch next)
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app.outputs.token }}
          fetch-depth: 0

      # 3) Git identity and EOL policy for consistent formatting
      - name: Configure Git identity & LF endings
        run: |
          set -eux
          git config user.name  "elis-bot"
          git config user.email "elis-bot@users.noreply.github.com"
          # Enforce LF endings to avoid Black churn across OSes
          git config core.autocrlf false
          git config core.eol lf

      # 4) Prepare target branch:
      #    - If origin/TARGET exists, check it out.
      #    - Otherwise create from origin/BASE and push it.
      - name: Prepare target branch
        run: |
          set -eux
          BASE="${BASE_BRANCH:-main}"
          HEAD="${TARGET_BRANCH:-elis-bot}"

          git fetch origin --prune
          git reset --hard
          git clean -fdx

          if git ls-remote --exit-code --heads origin "$HEAD" >/dev/null 2>&1; then
            git checkout -B "$HEAD" "origin/$HEAD"
          else
            git checkout -B "$HEAD" "origin/$BASE"
            git push -u origin "$HEAD"
          fi

      # 5) Sync target from base (rebase; if it fails/unrelated, reset to base)
      - name: Sync target from base (rebase or reset)
        run: |
          set -eux
          BASE="${BASE_BRANCH:-main}"
          git fetch origin "$BASE" --depth=1
          if ! git rebase "origin/$BASE"; then
            git rebase --abort || true
            echo "Rebase failed or unrelated histories; resetting to origin/$BASE"
            git reset --hard "origin/$BASE"
          fi

      # 6) Normalise line endings per .gitattributes (prevents Black 'would reformat')
      - name: Normalise line endings (.gitattributes)
        run: |
          set -eux
          git add --renormalize .
          if ! git diff --cached --quiet; then
            git commit -m "chore(format): normalise line endings per .gitattributes"
          else
            echo "No line-ending normalisation needed."
          fi

      # 7) Set up Python and Black
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Black
        run: |
          set -eux
          python -m pip install --upgrade pip
          pip install black==24.8.0

      # 8) Run Black in-place
      - name: Run Black (format in-place)
        run: black .

      # 9) Commit and push (use --force-with-lease only if ahead)
      - name: Commit and push formatting changes
        run: |
          set -eux
          HEAD="${TARGET_BRANCH:-elis-bot}"

          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(format): apply Black autoformat"
          fi

          AHEAD=$(git rev-list --left-only --count "origin/$HEAD..HEAD" || echo 0)
          if [ "$AHEAD" -gt 0 ]; then
            git push --force-with-lease origin HEAD:"$HEAD"
            echo "Pushed: $(git rev-parse --short HEAD)"
          else
            echo "No changes to push."
          fi

      # 10) Compare base..head (skip PR when no diff)
      - name: Compare base..head (API)
        id: compare
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.app.outputs.token }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const base  = process.env.BASE_BRANCH || 'main';
            const head  = process.env.TARGET_BRANCH || 'elis-bot';

            const cmp = await github.rest.repos.compareCommitsWithBasehead({
              owner, repo, basehead: `${base}...${head}`,
            });

            const hasDiff = (cmp.data.ahead_by > 0) || ((cmp.data.files || []).length > 0);
            core.setOutput('has_diff', hasDiff ? 'true' : 'false');
            core.info(`Diff? ${hasDiff} (ahead_by=${cmp.data.ahead_by}, behind_by=${cmp.data.behind_by})`);

      # 11) Open/refresh PR only when there is a diff (prevents 422)
      - name: Open/refresh PR to base
        if: ${{ env.OPEN_PR == 'true' && steps.compare.outputs.has_diff == 'true' }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ steps.app.outputs.token }}
          script: |
            const owner = context.repo.owner;
            const repo  = context.repo.repo;
            const base  = process.env.BASE_BRANCH || 'main';
            const head  = process.env.TARGET_BRANCH || 'elis-bot';

            // If a PR already exists, do nothing
            const { data: openPRs } = await github.rest.pulls.list({
              owner, repo, state: 'open', base, head: `${owner}:${head}`,
            });

            if (openPRs.length > 0) {
              core.info(`PR already open: #${openPRs[0].number}`);
            } else {
              const { data: pr } = await github.rest.pulls.create({
                owner, repo, base, head,
                title: "chore(format): apply Black autoformat",
                body: "Automated formatting and line-ending normalisation by ELIS - Autoformat.",
              });
              core.info(`Opened PR #${pr.number}`);
            }

      # 12) No-diff note (job remains green without a PR)
      - name: No changes to PR
        if: ${{ steps.compare.outputs.has_diff != 'true' }}
        run: |
          echo "No commits between ${BASE_BRANCH:-main} and ${TARGET_BRANCH:-elis-bot} — PR not required."
