name: ELIS - Autoformat
# ============================================================================
# Purpose
#   Standardize code style: Ruff (lint/fix) and Black (format).
#   - pull_request: check-only (non-destructive).
#   - workflow_dispatch: optionally apply fixes and auto-commit.
#
# Notes
#   - Includes a dry-run/diff step so you can see what Black would change.
#   - When we create a commit, we now ALWAYS push it (no fragile "ahead" math).
#   - Enforces LF endings + .gitattributes renormalisation to avoid churn.
# ============================================================================

on:
  pull_request:
  workflow_dispatch:
    inputs:
      apply_fixes:
        description: "Apply fixes and auto-commit"
        type: boolean
        default: true
        required: true

permissions:
  contents: write  # needed to auto-commit when apply_fixes=true

jobs:
  autoformat:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install tools (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install "ruff==0.6.1" "black==24.8.0"

      # ---- Check-only on PRs (always non-destructive) ----
      - name: Ruff (check)
        if: github.event_name == 'pull_request'
        run: ruff check .

      - name: Black (check)
        if: github.event_name == 'pull_request'
        run: black --check .

      # ---- Apply fixes on manual dispatch (optional) ----
      - name: Ruff (fix)
        if: github.event_name == 'workflow_dispatch' && inputs.apply_fixes == true
        run: ruff check --fix .

      - name: Black (format)
        if: github.event_name == 'workflow_dispatch' && inputs.apply_fixes == true
        run: black .

      - name: Auto-commit formatting changes
        if: github.event_name == 'workflow_dispatch' && inputs.apply_fixes == true
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "style(autoformat): apply Black/Ruff formatting"
          file_pattern: .
