name: ELIS - Autoformat
# =============================================================================
# Purpose
#   Auto-format a target branch with Black + Ruff.
#   If apply_fixes=true, write changes and push so PR checks re-run and go green.
#
# Notes
#   - Pin Black/Ruff versions to avoid version drift with quality checks.
#   - Select the branch to format via the 'target_branch' input.
# =============================================================================

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "Branch to autoformat (in-place)"
        required: true
        default: "main"
      apply_fixes:
        description: "Write changes and push (true) or just check (false)"
        type: boolean
        default: true
        required: true

permissions:
  contents: write

concurrency:
  group: autoformat-${{ github.event.inputs.target_branch || github.ref }}
  cancel-in-progress: false

jobs:
  autoformat:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1) App token so we can push commits reliably
      - name: Mint installation token (GitHub App)
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ELIS_APP_ID }}
          private-key: ${{ secrets.ELIS_APP_PRIVATE_KEY }}

      # 2) Check out the *target branch*
      - name: Checkout repository (target branch)
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app.outputs.token }}
          ref: ${{ inputs.target_branch }}
          fetch-depth: 0

      # 3) Git identity for the commit we may create
      - name: Configure Git identity
        run: |
          git config user.name  "elis-bot"
          git config user.email "elis-bot@users.noreply.github.com"

      # 4) Tooling (PINNED)
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install formatters (pinned)
        run: |
          python -m pip install --upgrade pip
          pip install "black==24.4.2" "ruff==0.6.9"

      # 5) Run Ruff + Black (fix or check)
      - name: Run Black / Ruff
        env:
          APPLY_FIXES: "${{ inputs.apply_fixes }}"
        run: |
          set -eux
          if [ "${APPLY_FIXES}" = "true" ]; then
            ruff check --fix .
            black .
          else
            ruff check .
            black --check .
          fi

      # 6) Commit & push only if changes exist (apply_fixes=true)
      - name: Commit changes (if any)
        if: ${{ inputs.apply_fixes == true }}
        run: |
          set -eux
          if ! git diff --quiet; then
            git add -A
            git commit -m "style(autoformat): apply Black/Ruff formatting"
            git remote set-url origin "https://x-access-token:${{ steps.app.outputs.token }}@github.com/${{ github.repository }}"
            git push --force-with-lease
          else
            echo "No formatting changes."
          fi

      # 7) Step summary
      - name: Summary
        run: |
          echo "## Autoformat" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "- Target branch: \`${{ inputs.target_branch }}\`" >> "$GITHUB_STEP_SUMMARY"
          echo "- Apply fixes: \`${{ inputs.apply_fixes }}\`" >> "$GITHUB_STEP_SUMMARY"
