# ELIS - Autoformat
# Purpose:
#   Manually run Black on branch "elis-bot". If formatting changes occur,
#   push the commit and open a Pull Request from "elis-bot" -> "main".
# Notes:
#   - Uses the installed GitHub App (elis-bot-commits) to mint a fine-grained token.
#   - Logs show an explicit no-op message when nothing changes and print the
#     commit SHA when a commit is created.

name: ELIS - Autoformat

on:
  workflow_dispatch: {}

jobs:
  autoformat:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Mint installation token (GitHub App)
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ELIS_APP_ID }}
          private-key: ${{ secrets.ELIS_APP_PRIVATE_KEY }}

      - name: Checkout branch elis-bot
        uses: actions/checkout@v4
        with:
          ref: elis-bot
          token: ${{ steps.app.outputs.token }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black==24.8.0

      - name: Run Black (format in-place)
        run: black .

      - name: Detect changes
        id: changes
        run: |
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No formatting changes detected."
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
