name: ELIS — Auto-update bot PR

on:
  push:
    branches: [ main ]          # run whenever main changes
  schedule:
    - cron: "*/30 * * * *"      # optional: every 30 minutes
  workflow_dispatch:             # allow manual runs

permissions:
  contents: write
  pull-requests: write

jobs:
  update-bot-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Update ELIS Agent PR branch from main
        uses: actions/github-script@v7
        with:
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Find open PR(s) created from the bot branch
            const { data: prs } = await github.rest.pulls.list({
              owner, repo, state: 'open',
              head: `${owner}:bot/elis-agent-update`
            });

            if (!prs.length) {
              core.info('No open PR from bot/elis-agent-update.');
              return;
            }

            for (const pr of prs) {
              core.info(`Attempting to update PR #${pr.number} (base: ${pr.base.ref}, head: ${pr.head.ref})`);
              try {
                // Merge base into head (same as "Update branch" button)
                await github.rest.pulls.updateBranch({
                  owner, repo, pull_number: pr.number
                });
                core.info(`Updated PR #${pr.number}`);
              } catch (e) {
                core.warning(`Could not update PR #${pr.number}: ${e.message}`);
              }
            }
