name: ELIS - Bot Commit (direct to elis-bot via GitHub App)
# =============================================================================
# Purpose
#   Create or update ONE file on a working branch (default: elis-bot),
#   commit & push it, and (optionally) open/refresh a PR to main.
#
# Why this version
#   • Accepts EITHER base64 OR raw content (choose one) to avoid "base64: invalid input".
#   • Normalises line endings to LF to keep CI/Black stable.
#   • Commits only when content actually changed (idempotent).
#   • Opens PR only if there is a diff vs base (prevents 422 "No commits between ...").
# =============================================================================

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path (relative to repo root) of the file to create/update"
        required: true
      content_b64:
        description: "File content in Base64 (leave empty if using raw)"
        required: false
        default: ""
      content_raw:
        description: "File content as raw text (leave empty if using Base64). '\\n' becomes newline."
        required: false
        default: ""
      commit_message:
        description: "Commit message (conventional-commit style)"
        required: true
      base_branch:
        description: "Base branch"
        required: false
        default: "main"
      work_branch:
        description: "Working branch"
        required: false
        default: "elis-bot"
      open_pr:
        description: "Open/refresh PR work_branch → base_branch"
        required: false
        default: "true"

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-file:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # 1) Checkout base branch
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          fetch-depth: 0

      # 2) Configure Git identity
      - name: Configure Git identity
        run: |
          git config user.name  "elis-bot"
          git config user.email "elis-bot@users.noreply.github.com"

      # 3) Prepare working branch (create if missing)
      - name: Prepare working branch
        env:
          BASE: ${{ i
