name: ELIS - Bot Commit and PR (auto-merge, no-PAT)

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path to create/update (e.g., scripts/validate_json.py)"
        required: true
      content_base64:
        description: "Base64-encoded file content (single line)"
        required: true
      commit_message:
        description: "Commit message"
        required: true
      target_branch:
        description: "Base branch"
        required: false
        default: "main"
      pr_title:
        description: "Pull Request title"
        required: false
        default: "Automated update"
      pr_body:
        description: "Pull Request body"
        required: false
        default: "Automated update by ELIS Bot."

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest

    # Requires repo settings: Actions → Workflow permissions = Read & write,
    # and General → Pull Requests → Enable auto-merge (ON).
    permissions:
      contents: write
      pull-requests: write

    env:
      GH_TOKEN: ${{ github.token }}  # Built-in token for this repository
      GIT_AUTHOR_NAME: ELIS Bot
      GIT_AUTHOR_EMAIL: 233278419+elis-bot@users.noreply.github.com
      GIT_COMMITTER_NAME: ELIS Bot
      GIT_COMMITTER_EMAIL: 233278419+elis-bot@users.noreply.github.com

    steps:
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch }}

      - name: Prepare new branch name
        id: prep
        shell: bash
        run: |
          set -euo pipefail
          ts="$(date -u +'%Y%m%d-%H%M%S')"
          safe="$(echo "${{ inputs.commit_message }}" | tr ' ' '-' | tr -cd '[:alnum:]-_')"
          echo "branch=bot/${safe:-update}-${ts}" >> "$GITHUB_OUTPUT"

      - name: Create working branch
        run: git switch -c "${{ steps.prep.outputs.branch }}"

      - name: Write file content
        shell: bash
        run: |
          set -euo pipefail
          # Sanitize path: drop accidental "file_path:" prefix, trim spaces, squash //.
          raw="${{ inputs.file_path }}"
          fp="$(printf '%s' "$raw" | sed -E 's/^file_path:[[:space:]]*//; s#[[:space:]]+$##; s#//+#/#g')"
          mkdir -p "$(dirname "$fp")"
          # Decode allowing stray whitespace pasted in the UI.
          printf '%s' "${{ inputs.content_base64 }}" | base64 --decode --ignore-garbage > "$fp"
          # Ensure trailing newline (POSIX-friendly).
          tail -c1 "$fp" | read -r _ || echo >> "$fp"
          # Quick sanity checks.
          test -s "$fp" || { echo "Decoded file is empty"; exit 1; }
          git status --porcelain

      - name: Commit changes
        run: |
          git add -A
          git -c user.name="$GIT_AUTHOR_NAME" -c user.email="$GIT_AUTHOR_EMAIL" \
              commit -m "${{ inputs.commit_message }}"

      - name: Push branch
        run: git push --set-upstream origin "${{ steps.prep.outputs.branch }}"

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create \
            --title "${{ inputs.pr_title }}" \
            --body "${{ inputs.pr_body }}" \
            --base "${{ inputs.target_branch }}" \
            --head "${{ steps.prep.outputs.branch }}"

      - name: Enable auto-merge (squash) and complete if checks pass
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get PR URL and enable auto-merge with squash strategy.
          pr_url="$(gh pr view --json url -q .url)"
          gh pr merge "$pr_url" --squash --auto
          echo "Auto-merge enabled for: $pr_url"
