# ============================================================
# Workflow: ELIS - Bot Commit (direct to elis-bot via GitHub App)
# Purpose:
#   - Write/update a file on branch "elis-bot" and open a PR to "main".
#   - Uses a GitHub App token (no PAT).
# Notes:
#   - Comments in UK English. Paste as .github/workflows/bot-commit.yml
# ============================================================

name: ELIS - Bot Commit (direct to elis-bot via GitHub App)

on:
  workflow_dispatch:
    inputs:
      file_path:
        description: "Path to create/update (e.g., docs/NOTE.md)"
        type: string
        required: true
      content_raw:
        description: "File content (plain text; paste as-is)"
        type: string
        required: true
      commit_message:
        description: "Concise commit message"
        type: string
        required: true
      base_branch:
        description: "Base branch to branch from"
        type: string
        required: false
        default: "main"
      work_branch:
        description: "Working branch to push to"
        type: string
        required: false
        default: "elis-bot"
      open_pr:
        description: "Open/refresh PR from work_branch -> base_branch"
        type: boolean
        required: false
        default: true

permissions:
  contents: write
  pull-requests: write

jobs:
  commit-and-pr:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      # --------------------------------------------------------
      # 1) Mint installation token using the GitHub App secrets
      # --------------------------------------------------------
      - name: Mint installation token (GitHub App)
        id: app
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ELIS_APP_ID }}
          private-key: ${{ secrets.ELIS_APP_PRIVATE_KEY }}

      # --------------------------------------------------------
      # 2) Checkout the base branch with the App token
      # --------------------------------------------------------
      - name: Checkout base branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.base_branch }}
          token: ${{ steps.app.outputs.token }}
          fetch-depth: 0

      # --------------------------------------------------------
      # 3) Create or switch to the working branch
      # --------------------------------------------------------
      - name: Create/switch working branch
        run: |
          set -euo pipefail
          base="${{ inputs.base_branch }}"
          work="${{ inputs.work_branch }}"
          git fetch origin "$base" --depth=1
          if git ls-remote --exit-code --heads origin "$work" >/dev/null 2>&1; then
            git checkout "$work"
            git merge --ff-only "origin/$base" || true
          else
            git checkout -b "$work" "origin/$base"
          fi
          echo "On branch: $(git rev-parse --abbrev-ref HEAD)"

      # --------------------------------------------------------
      # 4) Write file content (raw string), ensure trailing newline
      # --------------------------------------------------------
      - name: Write file content
        env:
          FP: ${{ inputs.file_path }}
          RAW: ${{ inputs.content_raw }}
        run: |
          set -euo pipefail
          mkdir -p "$(dirname "$FP")"
          # Write content verbatim (no base64). GitHub preserves newlines in the input.
          printf "%s" "$RAW" > "$FP"
          # Ensure POSIX trailing newline
          tail -c1 "$FP" | read -r _ || echo >> "$FP"
          # Sanity check
          test -s "$FP"
          git status --porcelain

      # --------------------------------------------------------
      # 5) Commit and push (only if there are changes)
      # --------------------------------------------------------
      - name: Commit & push
        id: commit
        env:
          WORK_BRANCH: ${{ inputs.work_branch }}
        run: |
          set -euo pipefail
          if git diff --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "No changes to commit."
            exit 0
          fi
          git config user.name  "ELIS Bot"
          git config user.email "233278419+elis-bot@users.noreply.github.com"
          git add -A
          git commit -m "${{ inputs.commit_message }}"
          echo "changed=true" >> "$GITHUB_OUTPUT"
          git push origin "HEAD:${WORK_BRANCH}"
          echo "sha=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          echo "Pushed commit: $(git rev-parse --short HEAD)"

      # --------------------------------------------------------
      # 6) Create or refresh PR (optional)
      # --------------------------------------------------------
      - name: Open/refresh PR (work -> base)
        if: ${{ inputs.open_pr && steps.commit.outputs.changed == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app.outputs.token }}
          script: |
            const {owner, repo} = context.repo;
            const head = `${owner}:${{ inputs.work_branch }}`;
            const base = "${{ inputs.base_branch }}";
            const title = "${{ inputs.commit_message }}";
            const body  = "Automated update by ELIS Bot.";

            // Reuse existing PR if any
            const existing = await github.rest.pulls.list({ owner, repo, state: "open", head, base });
            if (existing.data.length > 0) {
              const pr = existing.data[0];
              core.notice(`PR already open: #${pr.number}`);
              return;
            }
            const pr = await github.rest.pulls.create({ owner, repo, head: "${{ inputs.work_branch }}", base, title, body });
            core.notice(`PR created: #${pr.data.number}`);
            // Optional label
            await github.rest.issues.addLabels({
              owner, repo, issue_number: pr.data.number, labels: ["bot"]
            })
