name: ELIS - API Preflight

on:
  workflow_dispatch:
    inputs:
      provider:
        description: "Which API to test (scopus | ieee | wos)"
        required: true
        default: "scopus"

permissions:
  contents: read

jobs:
  preflight:
    runs-on: ubuntu-latest
    env:
      SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
      IEEE_EXPLORE_API_KEY: ${{ secrets.IEEE_EXPLORE_API_KEY }}
      WEB_OF_SCIENCE_API_KEY: ${{ secrets.WEB_OF_SCIENCE_API_KEY }}

    steps:
      - name: Resolve inputs
        id: cfg
        run: |
          set -euo pipefail
          PROV="${{ inputs.provider }}"
          case "$PROV" in
            scopus|ieee|wos) ;;
            *) echo "Unsupported provider: $PROV"; exit 2 ;;
          esac
          echo "prov=$PROV" >> "$GITHUB_OUTPUT"

      - name: Preflight selected provider
        id: run
        run: |
          set -euo pipefail
          PROV="${{ steps.cfg.outputs.prov }}"
          TMP_BODY="$GITHUB_WORKSPACE/.preflight_body"
          : > "$TMP_BODY"
          HTTP=000

          case "$PROV" in
            scopus)
              HTTP="$(curl -sS -o "$TMP_BODY" -w '%{http_code}' \
                -H "X-ELS-APIKey: ${SCOPUS_API_KEY:?missing SCOPUS_API_KEY}" \
                "https://api.elsevier.com/content/search/scopus?query=TITLE-ABS-KEY(election)&count=1")"
              ;;
            ieee)
              : "${IEEE_EXPLORE_API_KEY:?missing IEEE_EXPLORE_API_KEY}"
              HTTP="$(curl -sS -o "$TMP_BODY" -w '%{http_code}' \
                "https://ieeexploreapi.ieee.org/api/v1/search/articles?apikey=${IEEE_EXPLORE_API_KEY}&format=json&max_records=1&querytext=blockchain")"
              ;;
            wos)
              : "${WEB_OF_SCIENCE_API_KEY:?missing WEB_OF_SCIENCE_API_KEY}"
              HTTP="$(curl -sS -o "$TMP_BODY" -w '%{http_code}' \
                -H "X-ApiKey: ${WEB_OF_SCIENCE_API_KEY}" \
                "https://api.clarivate.com/api/woslite?databaseId=WOS&usrQuery=TS=(election)&count=1")"
              ;;
          esac

          PREVIEW_FILE="$GITHUB_WORKSPACE/.preflight_preview"
          head -c 500 "$TMP_BODY" > "$PREVIEW_FILE" || true

          echo "http=$HTTP" >> "$GITHUB_OUTPUT"
          echo "preview_file=$PREVIEW_FILE" >> "$GITHUB_OUTPUT"

          # Ensure file exists (network OK enough to create body)
          test -f "$PREVIEW_FILE"

      - name: Step Summary
        run: |
          set -euo pipefail
          PROV="${{ steps.cfg.outputs.prov }}"
          HTTP="${{ steps.run.outputs.http }}"
          PREVIEW_FILE="${{ steps.run.outputs.preview_file }}"
          {
            printf "## API Preflight\n\n"
            printf "- Provider: **%s**\n" "$PROV"
            printf "- HTTP status: **%s**\n\n" "$HTTP"

            printf "### Quick interpretation\n"
            if [ "$HTTP" = "200" ]; then
              printf "✅ Key and endpoint look **OK**.\n\n"
            elif [ "$HTTP" = "401" ] || [ "$HTTP" = "403" ]; then
              printf "⚠️  **Not authorised**. For WoS this is normal until approval; otherwise check the key/entitlements.\n\n"
            elif [ "$HTTP" = "429" ]; then
              printf "⚠️  **Rate limited**. Reduce caps or raise ELIS_HTTP_SLEEP_S.\n\n"
            else
              printf "ℹ️  Received HTTP %s – see response preview below.\n\n" "$HTTP"
            fi

            printf "### Response preview (first 500 bytes)\n"
            printf "%s\n" '```'
            if [ -f "$PREVIEW_FILE" ]; then head -c 500 "$PREVIEW_FILE"; fi
            printf "\n%s\n" '```'
          } >> "$GITHUB_STEP_SUMMARY"

          case "$HTTP" in
            200) exit 0 ;;
            401|403|429) exit 1 ;;
            *) exit 1 ;;
          esac
