name: ELIS - Housekeeping
# ============================================================
# Workflow: ELIS - Housekeeping
# Purpose:
#   - Clean up old workflow runs and artifacts to keep the repo lean.
#   - Default behaviour: delete COMPLETED runs and artifacts older than N days.
#
# Triggers:
#   - Manual (workflow_dispatch) with options.
#   - Weekly schedule (Sunday 06:00 UTC).
#
# Permissions:
#   - actions: write (required to delete runs/artifacts)
#   - contents: read
#
# Notes:
#   - Uses the GitHub-provided token (${{ github.token }}) only.
#   - Dry-run supported to preview deletions.
#   - Concurrency guard prevents overlapping housekeeping runs.
#   - Step Summary provides quick counts in the Actions UI.
# ============================================================

on:
  workflow_dispatch:
    inputs:
      retention_days:
        description: "Delete items older than this many days"
        type: number
        default: 14
        required: true
      delete_runs:
        description: "Delete COMPLETED workflow runs older than retention_days"
        type: boolean
        default: true
        required: true
      delete_artifacts:
        description: "Delete artifacts older than retention_days"
        type: boolean
        default: true
        required: true
      dry_run:
        description: "Preview only (do not delete)"
        type: boolean
        default: true
        required: true

  # Weekly schedule: Sunday 06:00 UTC
  schedule:
    - cron: "0 6 * * 0"

# Prevent overlapping housekeeping executions (e.g., manual + scheduled)
concurrency:
  group: housekeeping-${{ github.ref }}
  cancel-in-progress: true

permissions:
  actions: write
  contents: read

jobs:
  housekeeping:
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------------
      # Resolve configuration (supports manual and scheduled runs)
      # --------------------------------------------------------
      - name: Resolve inputs / defaults
        id: cfg
        env:
          RET_DAYS_IN: ${{ inputs.retention_days }}
          DEL_RUNS_IN: ${{ inputs.delete_runs }}
          DEL_ARTS_IN: ${{ inputs.delete_artifacts }}
          DRY_RUN_IN:  ${{ inputs.dry_run }}
        run: |
          set -euo pipefail
          # When scheduled (no workflow_dispatch), inputs are empty; set defaults.
          RETENTION_DAYS="${RET_DAYS_IN:-14}"
          DELETE_RUNS="${DEL_RUNS_IN:-true}"
          DELETE_ARTIFACTS="${DEL_ARTS_IN:-true}"
          # For scheduled runs, default dry_run to false; for manual, respect input.
          DRY_RUN="${DRY_RUN_IN:-false}"

          # Basic sanity for retention bounds (defensive; adjust as desired)
          if ! [[ "$RETENTION_DAYS" =~ ^[0-9]+$ ]]; then
            echo "::error::retention_days must be an integer"; exit 1
          fi
          if (( RETENTION_DAYS < 1 )); then
            echo "::warning::retention_days < 1 coerced to 1"
            RETENTION_DAYS=1
          fi

          echo "retention_days=${RETENTION_DAYS}"        >> "$GITHUB_OUTPUT"
          echo "delete_runs=${DELETE_RUNS}"              >> "$GITHUB_OUTPUT"
          echo "delete_artifacts=${DELETE_ARTIFACTS}"    >> "$GITHUB_OUTPUT"
          echo "dry_run=${DRY_RUN}"                      >> "$GITHUB_OUTPUT"

          echo "Configuration:"
          echo "  retention_days  = ${RETENTION_DAYS}"
          echo "  delete_runs     = ${DELETE_RUNS}"
          echo "  delete_artifacts= ${DELETE_ARTIFACTS}"
          echo "  dry_run         = ${DRY_RUN}"

      # --------------------------------------------------------
      # Delete COMPLETED workflow runs older than retention_days
      # - Exposes counts via step outputs -> used in the final summary.
      # --------------------------------------------------------
      - name: Housekeep workflow RUNS
        id: runs
        if: ${{ steps.cfg.outputs.delete_runs == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            // Inputs are passed via environment from the previous step.
            const retentionDays = parseInt(process.env.RETENTION_DAYS || '14', 10);
            const dryRun        = (process.env.DRY_RUN === 'true');
            const cutoffMs      = Date.now() - retentionDays*24*60*60*1000;
            const cutoffIso     = new Date(cutoffMs).toISOString();

            const { owner, repo } = context.repo;
            core.info(`Deleting COMPLETED runs older than ${retentionDays} days (cutoff=${cutoffIso}, dry_run=${dryRun})`);

            let deleted = 0, scanned = 0, page = 1;
            for (;;) {
              const { data } = await github.rest.actions.listWorkflowRunsForRepo({
                owner, repo, per_page: 100, page, status: 'completed'
              });
              const runs = data.workflow_runs || [];
              if (!runs.length) break;

              for (const run of runs) {
                scanned++;
                const updatedAt = new Date(run.updated_at).getTime();
                if (updatedAt < cutoffMs) {
                  core.info(`- OLD run #${run.id} name="${run.name}" updated_at=${run.updated_at}`);
                  if (!dryRun) {
                    await github.rest.actions.deleteWorkflowRun({ owner, repo, run_id: run.id });
                  }
                  deleted++;
                }
              }
              page++;
            }

            core.notice(`Runs scanned: ${scanned} | Runs deleted: ${deleted} | dry_run=${dryRun}`);
            core.setOutput('scanned', String(scanned));
            core.setOutput('deleted', String(deleted));
        env:
          RETENTION_DAYS:  ${{ steps.cfg.outputs.retention_days }}
          DRY_RUN:         ${{ steps.cfg.outputs.dry_run }}

      # --------------------------------------------------------
      # Delete artifacts older than retention_days
      # - Exposes counts via step outputs -> used in the final summary.
      # --------------------------------------------------------
      - name: Housekeep ARTIFACTS
        id: arts
        if: ${{ steps.cfg.outputs.delete_artifacts == 'true' }}
        uses: actions/github-script@v7
        with:
          github-token: ${{ github.token }}
          script: |
            // Inputs are passed via environment from the previous step.
            const retentionDays = parseInt(process.env.RETENTION_DAYS || '14', 10);
            const dryRun        = (process.env.DRY_RUN === 'true');
            const cutoffMs      = Date.now() - retentionDays*24*60*60*1000;
            const cutoffIso     = new Date(cutoffMs).toISOString();

            const { owner, repo } = context.repo;
            core.info(`Deleting artifacts older than ${retentionDays} days (cutoff=${cutoffIso}, dry_run=${dryRun})`);

            let deleted = 0, scanned = 0, page = 1;
            for (;;) {
              const { data } = await github.rest.actions.listArtifactsForRepo({
                owner, repo, per_page: 100, page
              });
              const arts = data.artifacts || [];
              if (!arts.length) break;

              for (const art of arts) {
                scanned++;
                const updatedAt = new Date(art.updated_at).getTime();
                if (updatedAt < cutoffMs) {
                  core.info(`- OLD artifact #${art.id} name="${art.name}" updated_at=${art.updated_at}`);
                  if (!dryRun) {
                    await github.rest.actions.deleteArtifact({ owner, repo, artifact_id: art.id });
                  }
                  deleted++;
                }
              }
              page++;
            }

            core.notice(`Artifacts scanned: ${scanned} | Artifacts deleted: ${deleted} | dry_run=${dryRun}`);
            core.setOutput('scanned', String(scanned));
            core.setOutput('deleted', String(deleted));
        env:
          RETENTION_DAYS:  ${{ steps.cfg.outputs.retention_days }}
          DRY_RUN:         ${{ steps.cfg.outputs.dry_run }}

      # --------------------------------------------------------
      # Rich summary in the Actions UI (Step Summary)
      # --------------------------------------------------------
      - name: Summary
        run: |
          {
            echo "## Housekeeping completed"
            echo ""
            echo "- Retention: **${{ steps.cfg.outputs.retention_days }}** days"
            echo "- Delete runs? **${{ steps.cfg.outputs.delete_runs }}**"
            echo "- Delete artifacts? **${{ steps.cfg.outputs.delete_artifacts }}**"
            echo "- Dry run: **${{ steps.cfg.outputs.dry_run }}**"
            echo ""
            echo "### Counts"
            echo "- Runs: scanned **${{ steps.runs.outputs.scanned || '0' }}**, deleted **${{ steps.runs.outputs.deleted || '0' }}**"
            echo "- Artifacts: scanned **${{ steps.arts.outputs.scanned || '0' }}**, deleted **${{ steps.arts.outputs.deleted || '0' }}**"
          } >> "$GITHUB_STEP_SUMMARY"
