# .github/workflows/projects-autoadd.yml
# ELIS — Projects Auto-Add
#
# What this does (fully automated):
#   • When an Issue/PR is OPENED, REOPENED, or LABELLED with `ELIS-Validation` or `ci`,
#     it is added to your ELIS Project (v2) and given a sensible Status.
#       - PR  → Status = "In review"
#       - Issue → Status = "To do"
#
# Requirements (explained here so you have everything in one place):
#   1) Repository variable  PROJECT_ID  set to your Project (v2) ID.
#   2) A classic PAT (personal access token) stored as a repo secret  PROJECTS_TOKEN
#      with scopes:  repo , project  (needed for user-owned Projects v2).
#      The workflow will automatically fall back to GITHUB_TOKEN if the secret
#      is missing, but you will otherwise see “Resource not accessible by integration”.
#
# Notes:
#   • Safe to re-run: all mutations are idempotent.
#   • Uses the GitHub CLI (`gh`) + GraphQL; jq is used to extract IDs.

name: ELIS - Projects Auto-Add

on:
  issues:
    types: [opened, reopened, labeled]
  pull_request:
    types: [opened, reopened, labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write
  repository-projects: write  # classic repo projects; PAT covers Projects v2

jobs:
  add_and_set_status:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      # Prefer PAT (PROJECTS_TOKEN). If not set, fall back to GITHUB_TOKEN.
      GH_TOKEN: ${{ secrets.PROJECTS_TOKEN != '' && secrets.PROJECTS_TOKEN || secrets.GITHUB_TOKEN }}

    steps:
      - name: Tooling
        run: |
          gh --version
          jq --version

      - name: Determine item type and node id
        id: ids
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            echo "TYPE=issue" >> $GITHUB_OUTPUT
            echo "NUM=${{ github.event.issue.number }}" >> $GITHUB_OUTPUT
            CID=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} --jq .node_id)
          else
            echo "TYPE=pr" >> $GITHUB_OUTPUT
            echo "NUM=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            CID=$(gh api repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} --jq .node_id)
          fi
          echo "CID=$CID" >> $GITHUB_OUTPUT
          echo "Content node id: $CID"

      - name: Read labels and (if matching) ensure item is on the Project
        id: add
        run: |
          CID="${{ steps.ids.outputs.CID }}"

          # Collect labels (Issues and PRs are Labelable)
          LABS=$(gh api graphql -f query='
            query($id:ID!){
              node(id:$id){
                ... on Labelable{ labels(first:100){ nodes{ name } } }
              }
            }' -f id="$CID" --jq '.data.node.labels.nodes[].name' | tr '\n' ' ' | tr -s ' ')
          echo "Labels: $LABS"

          case " $LABS " in
            *" ELIS-Validation "*|*" ci "*)
              echo "→ Matching label found; making sure the item is in the Project."
              gh api graphql -f query='mutation($pid:ID!,$cid:ID!){
                addProjectV2ItemById(input:{projectId:$pid,contentId:$cid}){ item { id } }
              }' -f pid="$PROJECT_ID" -f cid="$CID" >/dev/null 2>&1 || true
              echo "ADDED=1" >> $GITHUB_OUTPUT
            ;;
            *)
              echo "→ No matching labels; skipping add for now."
              echo "ADDED=0" >> $GITHUB_OUTPUT
            ;;
          esac

      # ─────────────────────────────────────────────────────────────────────
      # Helper: find the Project item for this content node id (CID)
      - name: Resolve Project item id
        id: item
        run: |
          CID="${{ steps.ids.outputs.CID }}"
          # List items and pick the one whose content.id equals our node id
          ITEM_ID=$(
            gh api graphql -f query='
              query($pid:ID!){
                node(id:$pid){
                  ... on ProjectV2{
                    items(first:200){
                      nodes{
                        id
                        content{
                          __typename
                          ... on Issue{ id }
                          ... on PullRequest{ id }
                        }
                      }
                    }
                  }
                }
              }' -f pid="$PROJECT_ID" \
            | jq -r --arg CID "$CID" '.data.node.items.nodes[] | select(.content.id==$CID) | .id' | head -n1
          )
          if [ -z "$ITEM_ID" ]; then
            echo "Project item not found yet. If this was just opened/labelled, it may appear on the next run."
          fi
          echo "ITEM_ID=$ITEM_ID" >> $GITHUB_OUTPUT
          echo "ITEM_ID=$ITEM_ID"

      # ─────────────────────────────────────────────────────────────────────
      # Fetch Status field id and option ids (In review / To do)
      - name: Cache Status field + option ids
        id: statusmeta
        run: |
          META=$(gh api graphql -f query='
            query($pid:ID!){
              node(id:$pid){
                ... on ProjectV2{
                  fields(first:50){
                    nodes{
                      __typename
                      id
                      name
                      ... on ProjectV2SingleSelectField { options { id name } }
                    }
                  }
                }
              }
            }' -f pid="$PROJECT_ID")
          STATUS_FIELD_ID=$(echo "$META" | jq -r '.data.node.fields.nodes[] | select(.name=="Status") | .id')
          INREVIEW_ID=$(echo "$META" | jq -r '.data.node.fields.nodes[] | select(.name=="Status") | .options[] | select(.name=="In review") | .id')
          TODO_ID=$(echo "$META" | jq -r '.data.node.fields.nodes[] | select(.name=="Status") | .options[] | select(.name=="To do") | .id')
          echo "STATUS_FIELD_ID=$STATUS_FIELD_ID" >> $GITHUB_OUTPUT
          echo "INREVIEW_ID=$INREVIEW_ID" >> $GITHUB_OUTPUT
          echo "TODO_ID=$TODO_ID" >> $GITHUB_OUTPUT

      # ─────────────────────────────────────────────────────────────────────
      # PR opened/reopened → set Status = In review (only if labelled)
      - name: PR opened/reopened → In review
        if: steps.ids.outputs.TYPE == 'pr' && (github.event.action == 'opened' || github.event.action == 'reopened')
        run: |
          # Only proceed if we actually have an item id
          if [ -z "${{ steps.item.outputs.ITEM_ID }}" ]; then
            echo "No Project item resolved yet; skipping."
            exit 0
          fi
          gh api graphql -f query='mutation($pid:ID!,$iid:ID!,$fid:ID!,$oid:ID!){
            updateProjectV2ItemFieldValue(input:{
              projectId:$pid,itemId:$iid,fieldId:$fid,
              value:{singleSelectOptionId:$oid}
            }){ projectV2Item{ id } }
          }' \
          -f pid="$PROJECT_ID" \
          -f iid="${{ steps.item.outputs.ITEM_ID }}" \
          -f fid="${{ steps.statusmeta.outputs.STATUS_FIELD_ID }}" \
          -f oid="${{ steps.statusmeta.outputs.INREVIEW_ID }}"

      # PR is labelled later with a matching label → set Status = In review
      - name: PR labelled → In review
        if: steps.ids.outputs.TYPE == 'pr' && github.event.action == 'labeled' && (github.event.label.name == 'ci' || github.event.label.name == 'ELIS-Validation')
        run: |
          if [ -z "${{ steps.item.outputs.ITEM_ID }}" ]; then
            echo "No Project item resolved yet; skipping."
            exit 0
          fi
          gh api graphql -f query='mutation($pid:ID!,$iid:ID!,$fid:ID!,$oid:ID!){
            updateProjectV2ItemFieldValue(input:{
              projectId:$pid,itemId:$iid,fieldId:$fid,
              value:{singleSelectOptionId:$oid}
            }){ projectV2Item{ id } }
          }' \
          -f pid="$PROJECT_ID" \
          -f iid="${{ steps.item.outputs.ITEM_ID }}" \
          -f fid="${{ steps.statusmeta.outputs.STATUS_FIELD_ID }}" \
          -f oid="${{ steps.statusmeta.outputs.INREVIEW_ID }}"

      # Issue opened/reopened (and carries a matching label) → set Status = To do
      - name: Issue opened/reopened → To do
        if: steps.ids.outputs.TYPE == 'issue' && (github.event.action == 'opened' || github.event.action == 'reopened')
        run: |
          if [ -z "${{ steps.item.outputs.ITEM_ID }}" ]; then
            echo "No Project item resolved yet; skipping."
            exit 0
          fi
          gh api graphql -f query='mutation($pid:ID!,$iid:ID!,$fid:ID!,$oid:ID!){
            updateProjectV2ItemFieldValue(input:{
              projectId:$pid,itemId:$iid,fieldId:$fid,
              value:{singleSelectOptionId:$oid}
            }){ projectV2Item{ id } }
          }' \
          -f pid="$PROJECT_ID" \
          -f iid="${{ steps.item.outputs.ITEM_ID }}" \
          -f fid="${{ steps.statusmeta.outputs.STATUS_FIELD_ID }}" \
          -f oid="${{ steps.statusmeta.outputs.TODO_ID }}"
